#include "../BasicFunctions.h"
#include "../BasicFunctions_Math.h"
#include "../BasicFunctions_HistogramMaking.h"
#include "../BasicFunctions_SystemCommands.h"
#include "../HistogramSystematics2.h"
#include "../GraphStyleFunctions.h"

#include "../GeneralPlotDrawingStructs.h"
#include "../LimitScriptHeaderFiles/LimitScripts_ParametersStruct.h"
#include "../interpolate.h"

//SUSY functions/structures//
#include "../SUSYFunctions/SUSYFunctions_CompositeHeaderFiles.h"
#include "../LimitStructs/ScenarioDrawingParams.h"
#include "../LimitStructs/ScenarioDrawingParams.cc"
#include "../LimitScriptHeaderFiles/LimitScripts_SUSYStruct.h"
#include "../LimitStructs/SUSYT2LimitParams.h"
#include "../LimitStructs/SUSYT2LimitParams.cc"

#include "./ROCCurveSavingFunctions_General.h"
#include "./ROCCurveSavingFunctions_Specific.h"
#include "./StopFunctions_ROCCurves.h"
#include "./StopROCCurveFunctions.h"
#include "../PlotStrings.h"
#include "./StopStructs_ROCCurves.h"
#include "./ROCCurveMakingFunctions.h"
#include "../TreeLevelPlotting/MappingFunctions.h"
#include "../TreeLevelPlotting/TreeLevelDrawingManager.h"
#include "../TreeLevelPlotting/BinningFunctions.h"
#include "../PlotStrings_DrawCommands.h"