//
// File generated by rootcint at Thu Mar 20 10:11:35 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME StopDictTry2
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "StopDictTry2.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* StopDictTry2.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableStopDictTry2();

extern "C" void G__set_cpp_environmentStopDictTry2() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../../HeaderFiles/NewOviStopPlotSkimmer_Legacy.h");
  G__cpp_reset_tagtableStopDictTry2();
}
#include <new>
extern "C" int G__cpp_dllrevStopDictTry2() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncStopDictTry2 {
 public:
  G__Sizep2memfuncStopDictTry2(): p(&G__Sizep2memfuncStopDictTry2::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncStopDictTry2::*p)();
};

size_t G__get_sizep2memfuncStopDictTry2()
{
  G__Sizep2memfuncStopDictTry2 a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceStopDictTry2() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableStopDictTry2() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PFJet>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEPFJetcOallocatorlEPFJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEPFJetcOallocatorlEPFJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEPFJetcOallocatorlEPFJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEPFJetcOallocatorlEPFJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEPFJetcOallocatorlEPFJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLorentzVector>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Lepton>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlELeptoncOallocatorlELeptongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlELeptoncOallocatorlELeptongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlELeptoncOallocatorlELeptongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlELeptoncOallocatorlELeptongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlELeptoncOallocatorlELeptongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GenParticlePointers_St3>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GenParticleSt3Info>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<GenParticleSt3Info> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<GenParticleSt3Info,allocator<GenParticleSt3Info> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GenParticleSt1Info>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<GenParticleSt1Info> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<GenParticleSt1Info,allocator<GenParticleSt1Info> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GenParticle*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2F*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SmearPFJet>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESmearPFJetcOallocatorlESmearPFJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlESmearPFJetcOallocatorlESmearPFJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESmearPFJetcOallocatorlESmearPFJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlESmearPFJetcOallocatorlESmearPFJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESmearPFJetcOallocatorlESmearPFJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DiParticle>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEDiParticlecOallocatorlEDiParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEDiParticlecOallocatorlEDiParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEDiParticlecOallocatorlEDiParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<DiParticle> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<DiParticle,allocator<DiParticle> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,BasicEventInfo*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOBasicEventInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBasicEventInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,BasicEventInfo*,less<int> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOBasicEventInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBasicEventInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventMETInfo*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventMETInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventMETInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventMETInfo*,less<int> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventMETInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventMETInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventLepInfo*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventLepInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventLepInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventLepInfo*,less<int> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventLepInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventLepInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventJetInfo*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventJetInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventJetInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventJetInfo*,less<int> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventJetInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventJetInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventDiStructureInfo*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventDiStructureInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventDiStructureInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,EventDiStructureInfo*,less<int> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEintcOEventDiStructureInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventDiStructureInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TString>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TString,less<TString> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1F*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<LV>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<double> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TF1>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETF1cOallocatorlETF1gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETF1cOallocatorlETF1gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETF1cOallocatorlETF1gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GenJet>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenJetcOallocatorlEGenJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenJetcOallocatorlEGenJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenJetcOallocatorlEGenJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenJetcOallocatorlEGenJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEGenJetcOallocatorlEGenJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HistogramT>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEHistogramTcOallocatorlEHistogramTgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEHistogramTcOallocatorlEHistogramTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEHistogramTcOallocatorlEHistogramTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlEHistogramTcOallocatorlEHistogramTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlEHistogramTcOallocatorlEHistogramTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SystT>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESystTcOallocatorlESystTgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlESystTcOallocatorlESystTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESystTcOallocatorlESystTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlESystTcOallocatorlESystTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESystTcOallocatorlESystTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TFile*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETFilemUcOallocatorlETFilemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETFilemUcOallocatorlETFilemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETFilemUcOallocatorlETFilemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlETFilemUcOallocatorlETFilemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlETFilemUcOallocatorlETFilemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<histKey,TH1*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH1mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<HistogramT,SampleT>,TH1*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH1mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<HistogramT,SampleT>,TH1*,less<pair<HistogramT,SampleT> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH1mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<histKey,TH2*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH2mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<HistogramT,SampleT>,TH2*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH2mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<HistogramT,SampleT>,TH2*,less<pair<HistogramT,SampleT> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH2mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<histKey,TH3*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH3mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH3mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<HistogramT,SampleT>,TH3*>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH3mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH3mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<HistogramT,SampleT>,TH3*,less<pair<HistogramT,SampleT> > >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH3mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH3mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SampleT,bool>",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplESampleTcOboolcOlesslESampleTgRcOallocatorlEpairlEconstsPSampleTcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SampleT,bool,less<SampleT> >",117,G__get_linked_tagnum(&G__StopDictTry2LN_maplESampleTcOboolcOlesslESampleTgRcOallocatorlEpairlEconstsPSampleTcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SampleT>",117,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESampleTcOallocatorlESampleTgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlESampleTcOallocatorlESampleTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESampleTcOallocatorlESampleTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StopDictTry2LN_reverse_iteratorlEvectorlESampleTcOallocatorlESampleTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StopDictTry2LN_vectorlESampleTcOallocatorlESampleTgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarStopDictTry2() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncStopDictTry2() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalStopDictTry2() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {
}

static void G__cpp_setup_func38() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcStopDictTry2() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
  G__cpp_setup_func38();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__StopDictTry2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEPFJetcOallocatorlEPFJetgRsPgR = { "vector<PFJet,allocator<PFJet> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEPFJetcOallocatorlEPFJetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PFJet,allocator<PFJet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR = { "vector<TLorentzVector,allocator<TLorentzVector> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLorentzVector,allocator<TLorentzVector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlELeptoncOallocatorlELeptongRsPgR = { "vector<Lepton,allocator<Lepton> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlELeptoncOallocatorlELeptongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Lepton,allocator<Lepton> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgR = { "vector<GenParticlePointers_St3,allocator<GenParticlePointers_St3> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<GenParticlePointers_St3,allocator<GenParticlePointers_St3> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgR = { "vector<GenParticleSt3Info,allocator<GenParticleSt3Info> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<GenParticleSt3Info,allocator<GenParticleSt3Info> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR = { "vector<vector<GenParticleSt3Info,allocator<GenParticleSt3Info> >,allocator<vector<GenParticleSt3Info,allocator<GenParticleSt3Info> > > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<GenParticleSt3Info,allocator<GenParticleSt3Info> >,allocator<vector<GenParticleSt3Info,allocator<GenParticleSt3Info> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgR = { "vector<GenParticleSt1Info,allocator<GenParticleSt1Info> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<GenParticleSt1Info,allocator<GenParticleSt1Info> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR = { "vector<vector<GenParticleSt1Info,allocator<GenParticleSt1Info> >,allocator<vector<GenParticleSt1Info,allocator<GenParticleSt1Info> > > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<GenParticleSt1Info,allocator<GenParticleSt1Info> >,allocator<vector<GenParticleSt1Info,allocator<GenParticleSt1Info> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgR = { "vector<GenParticle*,allocator<GenParticle*> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<GenParticle*,allocator<GenParticle*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR = { "vector<TH2F*,allocator<TH2F*> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2F*,allocator<TH2F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlESmearPFJetcOallocatorlESmearPFJetgRsPgR = { "vector<SmearPFJet,allocator<SmearPFJet> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlESmearPFJetcOallocatorlESmearPFJetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SmearPFJet,allocator<SmearPFJet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEDiParticlecOallocatorlEDiParticlegRsPgR = { "vector<DiParticle,allocator<DiParticle> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DiParticle,allocator<DiParticle> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR = { "vector<vector<DiParticle,allocator<DiParticle> >,allocator<vector<DiParticle,allocator<DiParticle> > > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<DiParticle,allocator<DiParticle> >,allocator<vector<DiParticle,allocator<DiParticle> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEintcOBasicEventInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBasicEventInfomUgRsPgRsPgR = { "map<int,BasicEventInfo*,less<int>,allocator<pair<const int,BasicEventInfo*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEintcOEventMETInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventMETInfomUgRsPgRsPgR = { "map<int,EventMETInfo*,less<int>,allocator<pair<const int,EventMETInfo*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEintcOEventLepInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventLepInfomUgRsPgRsPgR = { "map<int,EventLepInfo*,less<int>,allocator<pair<const int,EventLepInfo*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEintcOEventJetInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventJetInfomUgRsPgRsPgR = { "map<int,EventJetInfo*,less<int>,allocator<pair<const int,EventJetInfo*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEintcOEventDiStructureInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventDiStructureInfomUgRsPgRsPgR = { "map<int,EventDiStructureInfo*,less<int>,allocator<pair<const int,EventDiStructureInfo*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR = { "map<TString,TString,less<TString>,allocator<pair<const TString,TString> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR = { "vector<TH1F*,allocator<TH1F*> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1F*,allocator<TH1F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR = { "vector<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<double> >,allocator<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<double> > > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<double> >,allocator<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETF1cOallocatorlETF1gRsPgR = { "vector<TF1,allocator<TF1> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TF1,allocator<TF1> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEGenJetcOallocatorlEGenJetgRsPgR = { "vector<GenJet,allocator<GenJet> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEGenJetcOallocatorlEGenJetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<GenJet,allocator<GenJet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlEHistogramTcOallocatorlEHistogramTgRsPgR = { "vector<HistogramT,allocator<HistogramT> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlEHistogramTcOallocatorlEHistogramTgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HistogramT,allocator<HistogramT> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlESystTcOallocatorlESystTgRsPgR = { "vector<SystT,allocator<SystT> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlESystTcOallocatorlESystTgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SystT,allocator<SystT> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlETFilemUcOallocatorlETFilemUgRsPgR = { "vector<TFile*,allocator<TFile*> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlETFilemUcOallocatorlETFilemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TFile*,allocator<TFile*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH1mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH1mUgRsPgRsPgR = { "map<pair<HistogramT,SampleT>,TH1*,less<pair<HistogramT,SampleT> >,allocator<pair<const pair<HistogramT,SampleT>,TH1*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH2mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH2mUgRsPgRsPgR = { "map<pair<HistogramT,SampleT>,TH2*,less<pair<HistogramT,SampleT> >,allocator<pair<const pair<HistogramT,SampleT>,TH2*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH3mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH3mUgRsPgRsPgR = { "map<pair<HistogramT,SampleT>,TH3*,less<pair<HistogramT,SampleT> >,allocator<pair<const pair<HistogramT,SampleT>,TH3*> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_maplESampleTcOboolcOlesslESampleTgRcOallocatorlEpairlEconstsPSampleTcOboolgRsPgRsPgR = { "map<SampleT,bool,less<SampleT>,allocator<pair<const SampleT,bool> > >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_vectorlESampleTcOallocatorlESampleTgRsPgR = { "vector<SampleT,allocator<SampleT> >" , 99 , -1 };
G__linked_taginfo G__StopDictTry2LN_reverse_iteratorlEvectorlESampleTcOallocatorlESampleTgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SampleT,allocator<SampleT> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableStopDictTry2() {
  G__StopDictTry2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__StopDictTry2LN_TVectorTlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TVectorTlEdoublegR.tagnum = -1 ;
  G__StopDictTry2LN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEPFJetcOallocatorlEPFJetgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEPFJetcOallocatorlEPFJetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlELeptoncOallocatorlELeptongRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlELeptoncOallocatorlELeptongRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlESmearPFJetcOallocatorlESmearPFJetgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlESmearPFJetcOallocatorlESmearPFJetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEDiParticlecOallocatorlEDiParticlegRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEintcOBasicEventInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBasicEventInfomUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEintcOEventMETInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventMETInfomUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEintcOEventLepInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventLepInfomUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEintcOEventJetInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventJetInfomUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEintcOEventDiStructureInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventDiStructureInfomUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETF1cOallocatorlETF1gRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEGenJetcOallocatorlEGenJetgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEGenJetcOallocatorlEGenJetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlEHistogramTcOallocatorlEHistogramTgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlEHistogramTcOallocatorlEHistogramTgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlESystTcOallocatorlESystTgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlESystTcOallocatorlESystTgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlETFilemUcOallocatorlETFilemUgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlETFilemUcOallocatorlETFilemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH1mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH1mUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH2mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH2mUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH3mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH3mUgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_maplESampleTcOboolcOlesslESampleTgRcOallocatorlEpairlEconstsPSampleTcOboolgRsPgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_vectorlESampleTcOallocatorlESampleTgRsPgR.tagnum = -1 ;
  G__StopDictTry2LN_reverse_iteratorlEvectorlESampleTcOallocatorlESampleTgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableStopDictTry2() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEPFJetcOallocatorlEPFJetgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEPFJetcOallocatorlEPFJetgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlELeptoncOallocatorlELeptongRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlELeptoncOallocatorlELeptongRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlePointers_St3cOallocatorlEGenParticlePointers_St3gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRcOallocatorlEvectorlEGenParticleSt3InfocOallocatorlEGenParticleSt3InfogRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRcOallocatorlEvectorlEGenParticleSt1InfocOallocatorlEGenParticleSt1InfogRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenParticlemUcOallocatorlEGenParticlemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlESmearPFJetcOallocatorlESmearPFJetgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlESmearPFJetcOallocatorlESmearPFJetgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEDiParticlecOallocatorlEDiParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRcOallocatorlEvectorlEDiParticlecOallocatorlEDiParticlegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEintcOBasicEventInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBasicEventInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEintcOEventMETInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventMETInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEintcOEventLepInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventLepInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEintcOEventJetInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventJetInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEintcOEventDiStructureInfomUcOlesslEintgRcOallocatorlEpairlEconstsPintcOEventDiStructureInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETF1cOallocatorlETF1gRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEGenJetcOallocatorlEGenJetgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEGenJetcOallocatorlEGenJetgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlEHistogramTcOallocatorlEHistogramTgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlEHistogramTcOallocatorlEHistogramTgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlESystTcOallocatorlESystTgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlESystTcOallocatorlESystTgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlETFilemUcOallocatorlETFilemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlETFilemUcOallocatorlETFilemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH1mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH1mUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH2mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH2mUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplEpairlEHistogramTcOSampleTgRcOTH3mUcOlesslEpairlEHistogramTcOSampleTgRsPgRcOallocatorlEpairlEconstsPpairlEHistogramTcOSampleTgRcOTH3mUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_maplESampleTcOboolcOlesslESampleTgRcOallocatorlEpairlEconstsPSampleTcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_vectorlESampleTcOallocatorlESampleTgRsPgR);
   G__get_linked_tagnum_fwd(&G__StopDictTry2LN_reverse_iteratorlEvectorlESampleTcOallocatorlESampleTgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupStopDictTry2(void) {
  G__check_setup_version(30051515,"G__cpp_setupStopDictTry2()");
  G__set_cpp_environmentStopDictTry2();
  G__cpp_setup_tagtableStopDictTry2();

  G__cpp_setup_inheritanceStopDictTry2();

  G__cpp_setup_typetableStopDictTry2();

  G__cpp_setup_memvarStopDictTry2();

  G__cpp_setup_memfuncStopDictTry2();
  G__cpp_setup_globalStopDictTry2();
  G__cpp_setup_funcStopDictTry2();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncStopDictTry2();
  return;
}
class G__cpp_setup_initStopDictTry2 {
  public:
    G__cpp_setup_initStopDictTry2() { G__add_setup_func("StopDictTry2",(G__incsetup)(&G__cpp_setupStopDictTry2)); G__call_setup_funcs(); }
   ~G__cpp_setup_initStopDictTry2() { G__remove_setup_func("StopDictTry2"); }
};
G__cpp_setup_initStopDictTry2 G__cpp_setup_initializerStopDictTry2;

